### ISSUE TITLE
Question Regarding Docker Image: Can it be used in production?

### ISSUE THREAD

**Issue by arafath-mk** [open-webrtc-toolkit/owt-server#1001]
Can the docker images be used in production? Or is it just for evaluation purposes?

To be more specific, can I use the following readymade image for production?

https://hub.docker.com/r/openvisualcloud/xeon-ubuntu1804-service-owt

**Comment by andreasunterhuber** [comment]
@arafath-mk we have no experience with this docker image you mentioned, but it seems updated and maintained. I would give it a try. Otherwise create your own docker image. You can use https://github.com/open-webrtc-toolkit/owt-server/blob/master/docker/Dockerfile as a blueprint. We use a custom docker image (based on the named blueprint file) in production environment successfully.

**Comment by arafath-mk** [comment]
Thank you @andreasunterhuber
