### ISSUE TITLE
录制视频帧率是动态的，能固定帧率吗？

### ISSUE THREAD

**Issue by 516131179** [open-webrtc-toolkit/owt-server#115]

**Comment by daijh** [comment]
1. In 'mixing mode' or 'transcoding mode' recording, the frame rate is the same with owt-server mixing/transcoding frame rate.  This frame rate is fixed, and can be configured by client APIs.

2. In 'forward mode' recording, the frame rate is the exactly the same with origin publisher's video content. The frame rate is out of owt-server control, because of no transcoding in server side. If the publisher frame rate is fixed, the recording is fixed;  If not, the recording is variable frame rate.

Please use 'mixing mode' or 'transcoding mode' for fixed frame rate recording.

**Comment by xiandeatintel** [comment]
The recording framerate will be determined by the original stream at the publisher side without transcoding. and the framerate of the original stream may flucturate according to the network condition.
