### ISSUE TITLE
QUIC_TRANSPORT_PACKAGE_URL_PREFIX problem

### ISSUE THREAD

**Issue by Yansmiles** [open-webrtc-toolkit/owt-server#844]
QUIC_TRANSPORT_PACKAGE_URL_PREFIX is not defined
installCommonDeps.sh:317

**Comment by jianjunz** [comment]
Hi, it supposed to be defined as an environment variable of the URL prefix for pre-built [QUIC SDK](https://github.com/open-webrtc-toolkit/owt-deps-quic). Since there is not binary releases for QUIC SDK yet, you may either build it from source code, which may take a long time to download dependencies, or skip it and disable QUIC agent. To disable QUIC agent, please remove it from `start-all.sh` and set `enableWebTransport` to `false` in `management_api.toml`.
Sorry for the inconvenience caused.

**Comment by Yansmiles** [comment]
> Hi, it supposed to be defined as an environment variable of the URL prefix for pre-built [QUIC SDK](https://github.com/open-webrtc-toolkit/owt-deps-quic). Since there is not binary releases for QUIC SDK yet, you may either build it from source code, which may take a long time to download dependencies, or skip it and disable QUIC agent. To disable QUIC agent, please remove it from `start-all.sh` and set `enableWebTransport` to `false` in `management_api.toml`.
> Sorry for the inconvenience caused.

3Q
